### ISSUE TITLE
'react-scripts-kotlin' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by mykola-dev** [ScottHuangZL/my-kotlin-app#1]
Hi!
I'm trying to run the example.
I've cloned the repo. Then `npm start` and this error has been occurred:
```
'react-scripts-kotlin' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by ScottHuangZL** [comment]
Can you try 
npm i react-scripts-kotlin --save

**Comment by mykola-dev** [comment]
now it compiles, but web app generates html with this message:
./node_modules/.cache/kotlin-webpack/kotlinApp.js
Module not found: Can't resolve 'axios' in 'C:\dev\git\my-kotlin-app\node_modules\.cache\kotlin-webpack'

**Comment by mykola-dev** [comment]
never mind, i've done `npm install` and now it works.
thanks for help!
